[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "npm run build"
  publish = ".next"

  [[plugins]]
  package = "netlify-plugin-one"

  [[plugins]]
  package = "netlify-plugin-two"